#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = true
    default_indent = 4

    bootstrap_before = "myspacevim#init"
    bootstrap_after = "myspacevim#after"

    enable_neomake = false
    enable_ale = true
    enable_ycm = 1
    project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.gitignore', 'ci.json', 'config-ci.json']
    project_rooter_automatically = 1
    force_global_config = 1
    relativenumber = 1
    enable_language_specific_leader = 0
    github_username = '812lcl'
    filemanager = 'nerdtree'
    enable_vimfiler_gitstatus = 0
    enable_vimfiler_filetypeicon = 0
    windows_index_type = 2
    buffer_index_type = 4
    enable_statusline_mode = 1
    snippet_engine = "ultisnips"
    disabled_plugins = ["clever-f.vim", "limelight.vim", "vnote", "wildfire.vim"]

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "smart"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'denite'

[[layers]]
name = 'git'

[[layers]]
name = 'github'

[[layers]]
name = 'sudo'

[[layers]]
name = 'tmux'

[[layers]]
name = 'tools'

[[layers]]
name = 'tools#dash'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'shell'
default_position = 'top'
default_hight = 30

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#json'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#vim'

[[layers]]
name = 'lang#xml'

[[layers]]
name = 'tags'

[[layers]]
name = 'fzf'

[[custom_plugins]]
name = "skywind3000/vim-keysound"

[[custom_plugins]]
name = "wakatime/vim-wakatime"

[[custom_plugins]]
name = "gorodinskiy/vim-coloresque"

[[custom_plugins]]
name = "osyo-manga/vim-anzu"

[[custom_plugins]]
name = "rdnetto/YCM-Generator"

[[custom_plugins]]
name = "AndrewRadev/splitjoin.vim"

[[custom_plugins]]
name = "vim-scripts/TaskList.vim"

[[custom_plugins]]
name = "tpope/vim-projectionist"

[[custom_plugins]]
name = "SpaceVim/nvim-yarp"

[[custom_plugins]]
name = "SpaceVim/vim-hug-neovim-rpc"

[[custom_plugins]]
name = "tweekmonster/startuptime.vim"
