#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "neosolarized"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = true
    default_indent = 4

    bootstrap_before = "myspacevim#init"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'cscope'

[[layers]]
name = 'denite'

[[layers]]
name = 'git'

[[layers]]
name = 'chinese'

[[layers]]
name = 'incsearch'
enable = true

[[layers]]
name = 'sudo'

[[layers]]
name = 'tags'

[[layers]]
name = 'tmux'

[[layers]]
name = 'tools'

[[layers]]
name = 'tools#dash'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'unite'

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#json'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#vim'

[[layers]]
name = 'lang#xml'
