#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "molokai"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    enable_statusline_display_mode = true
    enable_statusline_mode = 1
    wrap_line = true
    windows_smartclose = 'q'
    statusline_left_sections = [
        'winnr',
        'filename',
        'major mode',
        'search count',
        'minor mode lighters',
        'version control info'
    ]
    statusline_right_sections = [
        'fileformat',
        'cursorpos',
        'percentage',
        'syntax checking',
        'whitespace'
    ]
    enable_tabline_filetype_icon = true
    default_indent = 4

    bootstrap_before = "myspacevim#init"
    bootstrap_after = "myspacevim#after"

    lint_engine = 'ale'
    lint_on_the_fly = true
    error_symbol = '✖'
    warning_symbol = '⚠'
    info_symbol = 'ⓘ'
    enable_ycm = 1
    autocomplete_method = 'ycm'
    autocomplete_parens = 1
    project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.gitignore', 'ci.json', 'config-ci.json', 'go.mod', 'go.sum']
    project_rooter_automatically = 1
    project_rooter_outermost = false
    force_global_config = 1
    relativenumber = 1
    enable_language_specific_leader = 0
    github_username = '812lcl'
    filemanager = 'defx'
    enable_vimfiler_welcome = false
    enable_vimfiler_gitstatus = 0
    enable_vimfiler_filetypeicon = 1
    windows_index_type = 2
    buffer_index_type = 4
    snippet_engine = "ultisnips"
    disabled_plugins = ["clever-f.vim", "vim-scriptease", "vimloo", "vnote", "wildfire.vim", "ChineseLinter.vim", "tagbar", "tagbar-makefile.vim", "tagbar-proto.vim", "tagbar-markdown", "vim-emoji", "editorconfig-vim", "deoplete-dictionary", "neco-syntax", "neco-vim", "neoinclude.vim", "neopairs.vim", "neosnippet-snippets", "vim-jplus", "vim-dispatch", "vimshell.vim", "vim-node-rpc", "vim-smoothie"]
    todo_labels = ['TODO', 'FIXME', '@bug', '@question', '@idea', '@fixme']

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "smart"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'checkers'

[[layers]]
name = 'format'
enable = true

[[layers]]
name = 'edit'

[[layers]]
name = 'ui'

[[layers]]
name = 'core'
enable_smooth_scrolling = false

[[layers]]
name = 'core#banner'
enable = false

[[layers]]
name = 'core#tabline'

[[layers]]
name = 'core#statusline'
# above layers are default layers

# [[layers]]
# name = 'fzf'

[[layers]]
name = 'leaderf'

[[custom_plugins]]
name = "Yggdroot/LeaderF-marks"

[[layers]]
name = 'git'
git-plugin = "gina"

[[layers]]
name = 'tools#dash'

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#json'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'lang#lua'

[[layers]]
name = 'tags'

[[custom_plugins]]
name = "wakatime/vim-wakatime"

[[custom_plugins]]
name = "rdnetto/YCM-Generator"

[[custom_plugins]]
name = "tpope/vim-projectionist"

[[custom_plugins]]
name = "tweekmonster/startuptime.vim"
on_cmd = 'StartupTime'

[[custom_plugins]]
name = "osyo-manga/vim-anzu"

[[custom_plugins]]
name = "kshenoy/vim-signature"

[[custom_plugins]]
name = "skywind3000/vim-terminal-help"

[[custom_plugins]]
name = "skywind3000/vim-keysound"

[[custom_plugins]]
name = "skywind3000/asyncrun.vim"
on_cmd = ['AsyncRun', 'AsyncStop']

[[custom_plugins]]
name = "skywind3000/asynctasks.vim"
on_cmd = ['AsyncTask', 'AsyncTaskMacro', 'AsyncTaskList', 'AsyncTaskEdit']

[[custom_plugins]]
name = "gorodinskiy/vim-coloresque"
on_ft = ['vim']

[[custom_plugins]]
name = "kana/vim-textobj-function"

[[custom_plugins]]
name = "sgur/vim-textobj-parameter"

[[custom_plugins]]
name = "voldikss/vim-floaterm"
