#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = true
    default_indent = 4

    bootstrap_before = "myspacevim#init"
    bootstrap_after = "myspacevim#after"

    enable_neomake = false
    enable_ale = true
    error_symbol = '✖'
    warning_symbol = '⚠'
    info_symbol = 'ⓘ'
    enable_ycm = 1
    autocomplete_method = 'ycm'
    project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.gitignore', 'ci.json', 'config-ci.json']
    project_rooter_automatically = 1
    force_global_config = 1
    relativenumber = 1
    enable_language_specific_leader = 0
    github_username = '812lcl'
    filemanager = 'vimfiler'
    enable_vimfiler_welcome = false
    enable_vimfiler_gitstatus = 0
    enable_vimfiler_filetypeicon = 0
    windows_index_type = 2
    buffer_index_type = 4
    enable_statusline_mode = 1
    snippet_engine = "ultisnips"
    disabled_plugins = ["clever-f.vim", "vim-scriptease", "vimloo", "vnote", "wildfire.vim", "ChineseLinter.vim", "tagbar", "tagbar-makefile.vim", "tagbar-proto.vim", "tagbar-markdown", "vim-emoji", "editorconfig-vim", "deoplete-dictionary", "neco-syntax", "neco-vim", "neoinclude.vim", "neopairs.vim", "neosnippet-snippets", "vim-jplus", "vim-dispatch", "vimshell.vim"]
    autocomplete_parens = 1

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "smart"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'checkers'

[[layers]]
name = 'format'
enable = true

[[layers]]
name = 'edit'

[[layers]]
name = 'ui'

[[layers]]
name = 'core'

[[layers]]
name = 'core#banner'
enable = false

[[layers]]
name = 'core#tabline'

[[layers]]
name = 'core#statusline'
# above layers are default layers

# [[layers]]
# name = 'denite'

# [[layers]]
# name = 'fzf'

[[layers]]
name = 'leaderf'

[[layers]]
name = 'git'
git-plugin = "fugitive"

[[layers]]
name = 'tmux'

[[layers]]
name = 'tools#dash'

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'shell'
default_position = 'bottom'
default_hight = 30

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#json'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'lang#lua'

[[layers]]
name = 'tags'

[[custom_plugins]]
name = "skywind3000/vim-keysound"

[[custom_plugins]]
name = "wakatime/vim-wakatime"

[[custom_plugins]]
name = "rdnetto/YCM-Generator"

[[custom_plugins]]
name = "AndrewRadev/splitjoin.vim"

[[custom_plugins]]
name = "tpope/vim-projectionist"

[[custom_plugins]]
name = "SpaceVim/nvim-yarp"

[[custom_plugins]]
name = "SpaceVim/vim-hug-neovim-rpc"

[[custom_plugins]]
name = "tweekmonster/startuptime.vim"
on_cmd = 'StartupTime'

[[custom_plugins]]
name = "osyo-manga/vim-anzu"

[[custom_plugins]]
name = "simnalamburt/vim-mundo"

[[custom_plugins]]
name = "Yggdroot/LeaderF-marks"

[[custom_plugins]]
name = "kshenoy/vim-signature"

[[custom_plugins]]
name = "skywind3000/vim-terminal-help"
